#!/bin/bash

DELAY=5
echo -e "`date` Calling vlc in $DELAY seconds"
sleep $DELAY

find /home/giz/Music -type d -name "ignore" -prune -o -type f -name "*.mp3" -print > /home/giz/Music/autoGeneratedPlaylist.m3u

/usr/bin/cvlc --audio-filter compressor --ignore-config  --loop --random /home/giz/Music/autoGeneratedPlaylist.m3u
echo `date` Finished $(realpath "$0")

