#!/usr/bin/env bash
set -u
set -o pipefail

########################################################################
# USER SETTINGS
###########/#############################################################
PLAYLIST="/home/giz/Music/autoGeneratedPlaylist.m3u"
FADE_START=30          # Start crossfade when 30 seconds remain in track
FADE_STEP=2            # Volume change percentage per step
FADE_DELAY=0.2         # higher means smoother mix
META_TIMEOUT=30        # Maximum seconds to wait for new VLC metadata/status update
POST_KILL_DELAY=5      # Delay after killing old VLC (seconds)
MIN_VOL=20
MAX_VOL=100
LAG_BETWEEN_FADES=4


########################################################################
# GLOBAL VARIABLE: active DBus destination for VLC
########################################################################
ACTIVE_DBUS="org.mpris.MediaPlayer2.vlc"

########################################################################
# HELPER FUNCTIONS
########################################################################

########################################
# Get current playback position in seconds
# Optional argument: DBus destination (default: ACTIVE_DBUS)
########################################
get_playback_time_s() {
  local dest="${1:-$ACTIVE_DBUS}"
  local pos_micro
  pos_micro=$(
    dbus-send --print-reply \
      --dest="$dest" \
      /org/mpris/MediaPlayer2 \
      org.freedesktop.DBus.Properties.Get \
      string:"org.mpris.MediaPlayer2.Player" \
      string:"Position" 2>/dev/null \
    | grep variant | awk '{print $3}'
  )
  if [[ -z "$pos_micro" ]]; then
    echo 0
  else
    echo $(( pos_micro / 1000000 ))
  fi
}




########################################
# Get total track length in seconds
# Optional argument: DBus destination (default: ACTIVE_DBUS)
########################################
get_track_length_s() {
  local dest="${1:-$ACTIVE_DBUS}"
  local metadata length_micro
  metadata=$(
    dbus-send --print-reply \
      --dest="$dest" \
      /org/mpris/MediaPlayer2 \
      org.freedesktop.DBus.Properties.Get \
      string:"org.mpris.MediaPlayer2.Player" \
      string:"Metadata" 2>/dev/null
  )
  length_micro=$(echo "$metadata" | awk '/mpris:length/{getline; print $3}')
  if [[ -z "$length_micro" ]]; then
    echo 0
  else
    echo $(( length_micro / 1000000 ))
  fi
}

########################################
# Get Track Name
########################################

get_track_name() {
  local dest="${1:-$ACTIVE_DBUS}"
  dbus-send --print-reply --dest="$dest" /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:"org.mpris.MediaPlayer2.Player" string:"Metadata" | grep mp3 | tail -1 | sed -n 's/.*string "\(.*\)"/\1/p'
}



########################################
# Get playback status ("Playing", "Paused", "Stopped")
# Optional argument: DBus destination (default: ACTIVE_DBUS)
########################################
get_playback_status() {
  local dest="${1:-$ACTIVE_DBUS}"
  dbus-send --print-reply \
    --dest="$dest" \
    /org/mpris/MediaPlayer2 \
    org.freedesktop.DBus.Properties.Get \
    string:"org.mpris.MediaPlayer2.Player" \
    string:"PlaybackStatus" 2>/dev/null \
  | grep string | sed 's/.*"\(.*\)".*/\1/'
}

########################################
# Set volume with dbus
########################################
set_volume_with_dbus() {
  local dest="${1:-$ACTIVE_DBUS}"
  local vol="$2"
  dbus-send --print-reply \
    --dest="$dest" \
    /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Set \
    string:"org.mpris.MediaPlayer2.Player" string:"Volume" variant:double:$vol.0  >/dev/null
  echo -e "[Debug] Set volume with dbus [$1,$2]"  >&2
}


#######################################
# resume playback
#######################################
resume_playback() {
  local dest="${1:-$ACTIVE_DBUS}"
  dbus-send --print-reply \
    --dest="$dest" \
    /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play  >/dev/null
  echo -e "[Debug] Resume playback"  >&2
}


########################################
# Get VLC instance's DBus name by PID using busctl
########################################
get_vlc_dbus_name() {
  local pid="$1"
  local name
  name=$(busctl --user list | awk -v p="$pid" '$0 ~ p && $1 ~ /^org.mpris.MediaPlayer2\.vlc\.instance/ {print $1; exit}')
  if [ -n "$name" ]; then
    echo "$name"
  else
    echo "org.mpris.MediaPlayer2.vlc"
  fi
}

########################################
# Launch a new VLC instance (PulseAudio output, with MPRIS enabled)
# Wait until its sink input is found and set its volume to 0%.
# Returns "PID:SINK" (stdout) where:
#   PID = VLC process id
#   SINK = PulseAudio sink-input index (without the leading "#")
########################################
start_vlc_instance() {
  echo "[DEBUG] Launching VLC instance with playlist: $PLAYLIST" >&2
  # Use --extraintf=mpris to force immediate MPRIS activation.
  cvlc --start-paused --extraintf=mpris --audio-filter compressor --aout=pulse --loop --random "$PLAYLIST" >/dev/null 2>&1 &
  local vlc_pid=$!
  echo "[DEBUG] Launched VLC, PID=$vlc_pid" >&2
  sleep 3
  NEW_DBUS=$(get_vlc_dbus_name "$vlc_pid")
  echo "$NEW_DBUS" > /tmp/active_vlc_dbus_name

  set_volume_with_dbus $NEW_DBUS 0
  sleep 3
  resume_playback $NEW_DBUS

  # Wait up to 15 seconds for PulseAudio to register the sink input.
  local timeout=15 elapsed=0 sink_input=""
  while [ "$elapsed" -lt "$timeout" ]; do
    sink_input=$(pactl list sink-inputs | awk -v pid="$vlc_pid" '
      /^Sink Input #[0-9]+/ {
         id = $3; sub(/^#/, "", id);
      }
      /application.process.id/ {
         gsub(/"/, "", $3);
         if ($3 == pid) { print id; exit }
      }')
    if [ -n "$sink_input" ]; then
      echo "[DEBUG] Found sink input $sink_input for VLC PID $vlc_pid" >&2
      break
    else
      echo "[DEBUG] Waiting for sink input for VLC PID $vlc_pid (elapsed ${elapsed}s)..." >&2
      sleep 1
      elapsed=$((elapsed + 1))
    fi
  done

  if [ -z "$sink_input" ]; then
    echo "[ERROR] Could not find sink input for VLC PID $vlc_pid after $timeout seconds" >&2
    return 1
  fi

  pactl set-sink-input-volume "$sink_input" 0%
  echo "[DEBUG] Set VLC PID $vlc_pid sink $sink_input volume to 0%" >&2

  # Return "PID:SINK"
  echo "${vlc_pid}:${sink_input}"
}

########################################
# Fade the volume of a sink input from start_vol% to end_vol%
########################################
fade_volume() {
  local sink_input="$1" start_vol="$2" end_vol="$3"
  echo "[DEBUG] Fading sink $sink_input from ${start_vol}% to ${end_vol}%" >&2
  local step=$FADE_STEP
  if [ "$start_vol" -gt "$end_vol" ]; then
    step=$(( -step ))
  fi
  local vol=$start_vol
  while true; do
    pactl set-sink-input-volume "$sink_input" "${vol}%"
    if [ "$step" -gt 0 ] && [ "$vol" -ge "$end_vol" ]; then break; fi
    if [ "$step" -lt 0 ] && [ "$vol" -le "$end_vol" ]; then break; fi
    vol=$((vol + step))
    sleep "$FADE_DELAY"
  done
}

########################################################################
# MAIN LOGIC
########################################################################

echo "[INFO] Starting initial VLC instance..." >&2

echo "preparing playlist..."
find /home/giz/Music -type d -name "ignore" -prune -o -type f -name "*.mp3" -print > $PLAYLIST

# Loop until we successfully get an instance with a valid sink input.
FIRST_INSTANCE=""
while [ -z "$FIRST_INSTANCE" ]; do
  FIRST_INSTANCE=$(start_vlc_instance)
  if [ -z "$FIRST_INSTANCE" ]; then
    echo "[ERROR] Failed to start VLC instance. Retrying in 5 seconds..." >&2
    sleep 5
  fi
done

ACTIVE_VLC_PID="${FIRST_INSTANCE%%:*}"
ACTIVE_SINK="${FIRST_INSTANCE##*:}"
ACTIVE_DBUS=$(get_vlc_dbus_name "$ACTIVE_VLC_PID")
TRACK_NAME=$(get_track_name "$ACTIVE_DBUS")

echo "[INFO] Initial VLC instance: PID=$ACTIVE_VLC_PID, Sink=$ACTIVE_SINK, DBus=$ACTIVE_DBUS, TrackName=$TRACK_NAME" >&2

fade_volume "$ACTIVE_SINK" 0 100
echo "[INFO] Set initial VLC (PID=$ACTIVE_VLC_PID) to 100% volume." >&2

while true; do
  PLAYBACK_TIME_S=$(get_playback_time_s "$ACTIVE_DBUS")
  TRACK_LENGTH_S=$(get_track_length_s "$ACTIVE_DBUS")
  STATUS=$(get_playback_status "$ACTIVE_DBUS")



  if [ -z "$TRACK_LENGTH_S" ] || [ "$TRACK_LENGTH_S" -eq 0 ]; then
    echo "[DEBUG] Could not read track length from $ACTIVE_DBUS. Possibly no track? Status=$STATUS" >&2
    sleep 2
    continue
  fi

  SECONDS_LEFT=$(( TRACK_LENGTH_S - PLAYBACK_TIME_S ))
  echo "[DEBUG] Active VLC ($ACTIVE_DBUS, PID=$ACTIVE_VLC_PID): Time=$PLAYBACK_TIME_S / $TRACK_LENGTH_S (left=${SECONDS_LEFT}s). Status=$STATUS" >&2

  # --- SKIP TRACK NOW CHECK ---
  if [ -f ~/skip_track_now ]; then
    skip_mod_time=$(stat -c %Y ~/skip_track_now)
    now=$(date +%s)
    if [ $(( now - skip_mod_time )) -lt 60 ]; then
      echo "[INFO] skip_track_now file detected (modified within last minute). Forcing crossfade." >&2
      SECONDS_LEFT=$FADE_START
    fi
    rm ~/skip_track_now
  fi
  # -----------------------------

  if [ "$SECONDS_LEFT" -le 0 ] || [ "$STATUS" = "Stopped" ]; then
    echo "[INFO] Track ended or VLC stopped. Waiting for next track..." >&2
    sleep 2
    continue
  fi

  if [ "$SECONDS_LEFT" -le "$FADE_START" ]; then

    echo "[INFO] Within $FADE_START seconds of track end. Spawning new VLC instance for crossfade." >&2
    SECOND_INSTANCE=$(start_vlc_instance)

    if [ -z "$SECOND_INSTANCE" ]; then
      echo "[ERROR] Failed to start new VLC instance. Retrying in 5 seconds..." >&2
      sleep 5
      continue
    fi
    NEW_VLC_PID="${SECOND_INSTANCE%%:*}"
    NEW_SINK="${SECOND_INSTANCE##*:}"
    NEW_DBUS=$(get_vlc_dbus_name "$NEW_VLC_PID")
    echo "$NEW_DBUS" > /tmp/active_vlc_dbus_name

    echo "[INFO] New VLC instance: PID=$NEW_VLC_PID, Sink=$NEW_SINK, DBus=$NEW_DBUS" >&2

    # Wait until the new instance reports status "Playing"
    new_attempt=0
    NEW_STATUS=$(get_playback_status "$NEW_DBUS")
    while [ "$NEW_STATUS" != "Playing" ] && [ "$new_attempt" -lt 10 ]; do
      echo "[DEBUG] Waiting for new VLC (PID=$NEW_VLC_PID, DBus=$NEW_DBUS) to report 'Playing' (attempt $new_attempt)..." >&2
      sleep 1
      NEW_STATUS=$(get_playback_status "$NEW_DBUS")
      new_attempt=$((new_attempt+1))
    done

    if [ "$NEW_STATUS" != "Playing" ]; then
      echo "[WARN] New VLC (PID=$NEW_VLC_PID) did not reach 'Playing' status. Proceeding with crossfade anyway." >&2
    else
      echo "[INFO] New VLC (PID=$NEW_VLC_PID) status is 'Playing'." >&2
    fi

    # Ensure the new VLC instance is muted before starting fade in.
    pactl set-sink-input-volume "$NEW_SINK" 0%
    echo "[DEBUG] Forced new VLC (PID=$NEW_VLC_PID) volume to 0%." >&2

    echo "[INFO] Starting crossfade sequence: fading in new track while fading out old track concurrently." >&2
    fade_volume "$NEW_SINK" $MIN_VOL $MAX_VOL &
    sleep $LAG_BETWEEN_FADES
    fade_volume "$ACTIVE_SINK" $MAX_VOL $MIN_VOL &
    wait

    echo "[INFO] Killing old VLC instance (PID=$ACTIVE_VLC_PID)..." >&2
    ####kill "$ACTIVE_VLC_PID" 2>/dev/null || echo "[WARN] Failed to kill old VLC PID $ACTIVE_VLC_PID" >&2


    ############## START OF KILL ################


    if kill -SIGTERM "$ACTIVE_VLC_PID" 2>/dev/null; then
	echo "Sent SIGTERM to VLC PID $ACTIVE_VLC_PID"
    else
	echo "[WARN] Failed to send SIGTERM to VLC PID $ACTIVE_VLC_PID" >&2
    fi

    # Wait a bit for VLC to exit gracefully
    sleep 5

    # Check if the process is still running
    if kill -0 "$ACTIVE_VLC_PID" 2>/dev/null; then
	echo "VLC PID $ACTIVE_VLC_PID is still running after SIGTERM, waiting an additional 5 seconds..." >&2
	sleep 5
	# Check again after additional waiting
	if kill -0 "$ACTIVE_VLC_PID" 2>/dev/null; then
	    # Attempt a forced shutdown with SIGKILL
	    if kill -9 "$ACTIVE_VLC_PID" 2>/dev/null; then
		echo "Sent SIGKILL to VLC PID $ACTIVE_VLC_PID" >&2

	    else
		echo "[WARN] Failed to kill VLC PID $ACTIVE_VLC_PID with SIGKILL" >&2
	    fi
	else
	    echo "VLC PID $ACTIVE_VLC_PID terminated gracefully after waiting." >&2

	fi
    else
	echo "VLC PID $ACTIVE_VLC_PID terminated gracefully." >&2

    fi

    ################# END OF KILL ###############

    sleep "$POST_KILL_DELAY"

    NEW_LENGTH=0
    attempt=0
    while [ "$attempt" -lt "$META_TIMEOUT" ]; do
      NEW_LENGTH=$(get_track_length_s "$NEW_DBUS")
      if [ "$NEW_LENGTH" -gt 0 ]; then
        echo "[INFO] New VLC metadata loaded: Track length = ${NEW_LENGTH}s." >&2
        break
      fi
      echo "[DEBUG] Attempt $attempt: New VLC ($NEW_DBUS, PID=$NEW_VLC_PID) has not loaded metadata yet." >&2
      sleep 1
      attempt=$((attempt + 1))
    done

    if [ "$NEW_LENGTH" -eq 0 ]; then
      echo "[WARN] New VLC instance ($NEW_DBUS, PID=$NEW_VLC_PID) did not load metadata after $META_TIMEOUT attempts." >&2
      echo "[INFO] Forcing track change by sending Next command to $NEW_DBUS." >&2
      dbus-send --print-reply --dest="$NEW_DBUS" \
        /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
      sleep 5
      NEW_LENGTH=$(get_track_length_s "$NEW_DBUS")
      if [ "$NEW_LENGTH" -gt 0 ]; then
        echo "[INFO] After forcing Next, new VLC metadata loaded: Track length = ${NEW_LENGTH}s." >&2
      else
        echo "[ERROR] Even after forcing Next, new VLC ($NEW_DBUS, PID=$NEW_VLC_PID) did not load metadata." >&2
      fi

    fi


    # Update active instance variables to new instance.
    ACTIVE_VLC_PID="$NEW_VLC_PID"
    ACTIVE_SINK="$NEW_SINK"
    ACTIVE_DBUS="$NEW_DBUS"
    TRACK_NAME=$(get_track_name "$ACTIVE_DBUS")

    echo "[INFO] Now active VLC instance is PID=$ACTIVE_VLC_PID, Sink=$ACTIVE_SINK, DBus=$ACTIVE_DBUS, TrackName=$TRACK_NAME." >&2
    sleep 2
  else
    sleep 2
  fi
done

## nir oren: https://github.com/niron1/boitpetit ##

